version: '3'
services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  
  keycloak:
    build:
      context: ./keycloak
    ports: 
      - "8080:8080"
    depends_on:
      - postgres